### ISSUE TITLE
There was an error when trying to unmarshal the API Error

### ISSUE THREAD

**Issue by RyuS3ki** [peimanja/artifactory_exporter#101]
#### Overview of the Issue

Related to [issue 84](https://github.com/peimanja/artifactory_exporter/issues/84)

Getting error:
```
level=debug ts=2023-03-03T12:36:15.040Z caller=utils.go:44 msg="Fetching http" path=https://artifactory.<domain>/api/system/license
level=error ts=2023-03-03T12:36:15.043Z caller=utils.go:57 msg="There was an error when trying to unmarshal the API Error" err="invalid character 'p' after top-level value"
```

#### Reproduction Steps

Helm install with following config:

- ARTI_ACCESS_TOKEN as existing Secret
- External artifactory URL with HTTPS
- ServiceMonitor enabled
- logLevel: debug
- RBAC & PSPs disabled

### Operating system and Environment details

Kubernetes GKE: `v1.24.8`
Helm: `v3`
Artifactory version: `7.49.5`
Exporter image version: `v1.12.0`
Exporter helm chart version: `0.5.0`

### Logs

```
level=debug ts=2023-03-03T12:36:15.040Z caller=utils.go:44 msg="Fetching http" path=https://artifactory.<domain>/api/system/license
level=error ts=2023-03-03T12:36:15.043Z caller=utils.go:57 msg="There was an error when trying to unmarshal the API Error" err="invalid character 'p' after top-level value"
```

**Comment by peimanja** [comment]
It's probably your Artifactory URL, you are missing `/artifactoy`, should be set to something like `url: https://artifactory.<domain>/artifactory`

**Comment by RyuS3ki** [comment]
Thank you, that worked!
