### ISSUE TITLE
Is Xray in scope for this project?

### ISSUE THREAD

**Issue by tomgeorge** [peimanja/artifactory_exporter#102]
We are piloting this repository, and have deployed this in our infrastructure and love the metrics that come out of the box. We would like to send some contributions upstream. I wanted to ask if Xray was explicitly out of scope for this project, or if you would welcome some Xray metric contributions?

**Comment by peimanja** [comment]
Hey @tomgeorge thanks for trying out this exporter. Xray is not currently under my radar but we are planning to use Xray more so I might get to that at some point this year. What type of metrics are you interested in?

This exporter supports optional metrics, so xray metrics can potentially get added as optional metrics and yes contributions are welcomed
