### ISSUE TITLE
Expand Repository Replication support

### ISSUE THREAD

**Issue by mymaor89** [peimanja/artifactory_exporter#111]
Please add replication metrics for Repository Replication

**Comment by peimanja** [comment]
So the following metric is already available:

Metric | Description | Labels | 
-- | -- | --|
artifactory_replication_enabled | Replication status for an Artifactory repository (1 = enabled). | name, type, cron_exp, status

the `status` label is only added if enabled. See https://github.com/peimanja/artifactory_exporter#optional-metrics
