### ISSUE TITLE
How to fetch information for each artifactory node?

### ISSUE THREAD

**Issue by PerGon** [peimanja/artifactory_exporter#114]
I feel this is a dummy question, sorry about it 😅 

We have artifactory running with 3 nodes. When I setup the `artifactory_exporter` the dashboard does not show all 3 nodes. When I look at the time-series `artifactory_system_license` I only get one value (I was expecting 3, one for each artifactory node).

We have configured the `artifactory_exporter` to fetch metrics from the artifactory service object.
Something like this:
```
  - name: ARTI_SCRAPE_URI
    value: http://artifactory-ha.artifactory:8081/artifactory
```

Where `artifactory-ha.artifactory` points to the service object of artifactory - which can then hit any of the available 3 nodes.

After looking around a bit, the conclusion I arrived was that to get metrics about the 3 nodes, I need to setup 3 instances of the `artifactory_exporter`, which one pointing directly to a different artifactory node.

Maybe this is too obvious, but can you confirm that to get info about each node, the `artifactory_exporter` has to be deployed in repeat, each instance pointing to a different artifactory node?

Thanks for the help.

**Comment by peimanja** [comment]
Your assumption is correct however since the license is stored in the database it should not matter which instance you are making the call.
