### ISSUE TITLE
user number is displayed with no data and the following artifacts are displayed to monitor no data

### ISSUE THREAD

**Issue by xujy1991** [peimanja/artifactory_exporter#122]
have deployed it, but the user number is displayed with no data and the following artifacts are displayed to monitor no data. Is my configuration file wrong? Prerequisite: I am open source version 7.29, non-paid

**Comment by xujy1991** [comment]
<img width="300" alt="企业微信截图_635add7e-2606-45fd-af1d-7c8b09c02013" src="https://github.com/peimanja/artifactory_exporter/assets/44825434/dabba443-990a-46f7-af6e-c0b43ce79987">
<img width="1439" alt="企业微信截图_e5b5ba3b-e1dd-440c-874e-657b0961bd4b" src="https://github.com/peimanja/artifactory_exporter/assets/44825434/6ee619ab-19ee-4487-a9f6-209b86db0f48">
<img width="1108" alt="企业微信截图_f21c155f-8d2b-417d-afee-a47ec7290ea6" src="https://github.com/peimanja/artifactory_exporter/assets/44825434/5afb1b15-6d22-45a8-a13e-a55355be9e6d">

**Comment by peimanja** [comment]
It's probably your [authentication](https://github.com/peimanja/artifactory_exporter?tab=readme-ov-file#authentication), check the logs and see if anything shows up there. 

you can also check [Common Issues](https://github.com/peimanja/artifactory_exporter?tab=readme-ov-file#authentication)
