### ISSUE TITLE
I have set environment variables, why is there still an error?

### ISSUE THREAD

**Issue by huangtc** [peimanja/artifactory_exporter#123]
![image](https://github.com/peimanja/artifactory_exporter/assets/41177222/036f6291-adc9-45d9-ac00-931742830538)

**Comment by peimanja** [comment]
Please refer to [Authentication](https://github.com/peimanja/artifactory_exporter?tab=readme-ov-file#authentication) doc. 

Either `ARTI_USERNAME` and `ARTI_PASSWORD` **OR** `ARTI_ACCESS_TOKEN` should be set
