### ISSUE TITLE
artifactory_storage_filestore_free_bytes calculating from cache

### ISSUE THREAD

**Issue by JyotsnaSharma21** [peimanja/artifactory_exporter#126]
Hi,

I am getting artifactory_storage_filestore_free_bytes value as  4 gbs, and it says around 15 is used. However, the storage type is "s3-storage-v3-direct". It is assuming that storage_dir="/opt/jfrog/artifactory/var/data/artifactory/cache". So, actually it is calculating the no.s from cache. I think this is a bit ambiguous. Can we get the how much has been consumed in total(on S3)?

**Comment by KacperPerschke** [comment]
@JyotsnaSharma21 please check [`percent`](https://github.com/KacperPerschke/artifactory_exporter/blob/22218443b8ad413adcfa5c02c380f0dbb766e26c/collector/storage.go#L64). I'm not sure if this answers your need. But may be?
