### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./artifactory_exporter)

### ISSUE THREAD

**Issue by althaser** [peimanja/artifactory_exporter#127]
**$ docker images |grep artifactory_exporter**
peimanja/artifactory_exporter                                          latest           **013ff29faee7**   5 days ago      34.8MB

**$ docker run peimanja/artifactory_exporter:latest -h**
./artifactory_exporter: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by ./artifactory_exporter)
./artifactory_exporter: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by ./artifactory_exporter)

**Comment by KacperPerschke** [comment]
### Reproduction attempt
```
$ docker image pull peimanja/artifactory_exporter
⋮
$ docker image ls peimanja/artifactory_exporter
REPOSITORY                      TAG       IMAGE ID       CREATED      SIZE
peimanja/artifactory_exporter   latest    013ff29faee7   9 days ago   34.8MB
$ docker run peimanja/artifactory_exporter:latest -h
./artifactory_exporter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./artifactory_exporter)
./artifactory_exporter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./artifactory_exporter)
```
### Initial diagnosis
[Dockerfile](https://github.com/peimanja/artifactory_exporter/blob/c8db671ae2f82b1cb4dc2724ecc52e6e82158def/Dockerfile) uses [golang:1.21](https://hub.docker.com/_/golang/tags?name=1.21), with `CGO_ENABLED=1` set, which means it compiles binaries dynamically linked to glibc. At the same time, Debian 11 was used as the base for the final image, which has an _older_ glibc than golang 21 wants to have.

### Solution?
There are two ways:
1. build statically linked
1. upgrade debian version

I'll try the first one.

**Comment by KacperPerschke** [comment]
Please watch #128.

**Comment by althaser** [comment]
Hi @KacperPerschke 

I just noticed your message now, I have built the image from your branch and it worked properly:

```
$ docker run Issue_127:latest -h
usage: artifactory_exporter [<flags>]

Flags:
  -h, --help                    Show context-sensitive help (also try
                                --help-long and --help-man).
      --log.format=logfmt       Output format of log messages. One of: [logfmt,
                                json]
      --log.level=info          Only log messages with the given severity or
                                above. One of: [debug, info, warn, error]
      --web.listen-address=":9531"  
                                Address to listen on for web interface and
                                telemetry.
      --web.telemetry-path="/metrics"  
                                Path under which to expose metrics.
      --artifactory.scrape-uri="http://localhost:8081/artifactory"  
                                URI on which to scrape JFrog Artifactory.
      --artifactory.ssl-verify  Flag that enables SSL certificate verification
                                for the scrape URI
      --artifactory.timeout=5s  Timeout for trying to get stats from JFrog
                                Artifactory.
      --optional-metric=metric-name ...  
                                optional metric to be enabled. Pass multiple
                                times to enable multiple optional metrics.
      --version                 Show application version.

```

thanks

**Comment by KacperPerschke** [comment]
@althaser wrote
> … from your branch and it worked properly …

Thanks.
