### ISSUE TITLE
level=ERROR msg="There was an issue calculating the value" metric=artifacts err="Could not recognise '' as multiplier"

### ISSUE THREAD

**Issue by mendesrawr** [peimanja/artifactory_exporter#139]
Hello, I was wondering if this is a bug or something I can quickly fix on my own I'm running this in a container with no issue until I noticed parsing errors from the api/storagesummary artifactory endpoint it was scraping. It seems to be having trouble parsing the last few json objects binariesSummary. 

https://jfrog.com/help/r/jfrog-rest-apis/get-storage-summary-info

docker run --env-file=file -p 9531:9531 peimanja/artifactory_exporter:latest --artifactory.scrape-uri=https://artifacts.com/artifactory --log.level=error
time=2024-04-16T20:17:25.706Z level=ERROR msg="The string was not recognized as a known multiplier." artifactory.number.multiplier=""
time=2024-04-16T20:17:25.707Z level=ERROR msg="There was an issue calculating the value" metric=binaries err="Could not recognise '' as multiplier"
time=2024-04-16T20:17:25.707Z level=ERROR msg="The string was not recognized as a known multiplier." artifactory.number.multiplier=""
time=2024-04-16T20:17:25.707Z level=ERROR msg="There was an issue calculating the value" metric=artifacts err="Could not recognise '' as multiplier"

    "fileStoreSummary": {
        "storageType": "s3-storage-v3-direct",
        "storageDirectory": "/opt/jfrog/artifactory/var/data/artifactory/cache",
        "totalSpace": "1.0 GB",
        "usedSpace": "1.0 GB (1.0%)",
        "freeSpace": "1.0 GB (1.0%)"
    },
    "binariesSummary": {
        "binariesCount": "1",
        "binariesSize": "288.09 MB",
        "artifactsSize": "288.09 MB",
        "optimization": "100%",
        "itemsCount": "44",
        "artifactsCount": "44"
    }
}

**Comment by mendesrawr** [comment]
Using latest release

**Comment by mendesrawr** [comment]
Got around this by using latest tar.gz release which doesnt seem to have the same problem the docker image does an updated docker image would be appreciated.

**Comment by peimanja** [comment]
@mendesrawr can you please give the latest `canary` image tag a try and let me know if you see the same issue there?

**Comment by mendesrawr** [comment]
@peimanja I tried with canary and got the same error:
docker run --env-file=password.txt -p 9531:9531 peimanja/artifactory_exporter:canary --artifactory.scrape-uri=

Another thing I noticed when running a docker build with the provided DockerFile the issue is consistent.  While working without issue is when installing and running  artifactory_exporter-v1.14.0-linux-amd64.tar.gz directly for example no issue here. Any idea how we can replicate this in new image to run in container.
 ./artifactory_exporter --artifactory.scrape-uri=  

Unable to find image 'peimanja/artifactory_exporter:canary' locally
canary: Pulling from peimanja/artifactory_exporter
Digest: sha256:9be91f4557f7e1ee21f64e2c40f09dc97c7abf29c770ce1398b6de4892e20dc7
Status: Downloaded newer image for peimanja/artifactory_exporter:canary
time=2024-04-18T15:32:21.638Z level=INFO msg="Starting artifactory_exporter" version="(version=canary, branch=refs/heads/master, revision=b9c0dbb48006b16a1a87347a2ba50d739ca244b5)"
time=2024-04-18T15:32:21.638Z level=INFO msg="Build context" context="(go=go1.21.8, user=github-actions, date=2024-03-24T17:34:35Z)"
time=2024-04-18T15:32:21.638Z level=INFO msg="Listening on address" address=:9531
time=2024-04-18T15:32:25.257Z level=ERROR msg="The string was not recognized as a known multiplier." artifactory.number.multiplier=""
time=2024-04-18T15:32:25.257Z level=ERROR msg="There was an issue calculating the value" metric=artifacts err="Could not recognise '' as multiplier"
time=2024-04-18T15:32:25.257Z level=ERROR msg="The string was not recognized as a known multiplier." artifactory.number.multiplier=""
time=2024-04-18T15:32:25.259Z level=ERROR msg="There was an issue calculating the value" metric=binaries err="Could not recognise '' as multiplier"

**Comment by KacperPerschke** [comment]
@mendesrawr as I wrote in #140 I hadn't thought about the case you came across.

_I'm sorry for inconvenience._

**Comment by KacperPerschke** [comment]
@peimanja My intention with the change proposed in #124 was to improve readability and make the code easier to maintain. Does the change I made achieve the goal, or does it obfuscate the code and make it harder to diagnose the problem?

**Comment by peimanja** [comment]
@KacperPerschke looks like there are a lot of edge cases but let's see if we can catch them for now

**Comment by mendesrawr** [comment]
@peimanja @KacperPerschke Thank you so much the latest docker image works perfectly now. I really appreciate it. Later this week I'm going to try to replicate this build with a custom image.
