### ISSUE TITLE
Would this work for Artifactory Pro?

### ISSUE THREAD

**Issue by binnythomas-1989** [peimanja/artifactory_exporter#18]

**Comment by peimanja** [comment]
I have tested this with OSS and Enterprise versions. However, all the API endpoints available in Enterprise should be available in Pro. So yes, give it a try and let me know how that goes.

**Comment by binnythomas-1989** [comment]
I just received this error.

level=info ts=2020-01-16T11:36:26.175Z caller=main.go:30 msg="Listening on address" address=:9531
level=error ts=2020-01-16T11:36:44.145Z caller=collector.go:186 msg="Can't scrape Artifactory when fetching system/license" err="Get http://localhost:8081/artifactory/api/system/license: dial tcp 127.0.0.1:8081: connect: connection refused"

**Comment by peimanja** [comment]
@binnythomas-1989, by looking at the logs looks like artifactory is not running on ` http://localhost:8081/artifactory`.
You can set that by `--artifactory.scrape-uri` flag or `ARTI_SCRAPE_URI` environment variable.

**Comment by mfominov** [comment]
We got Artifactory Pro
information from System Info
artifactory.running.mode: | PRO

exporter work's fine.

Thx a lot for your job

**Comment by binnythomas-1989** [comment]
I ended up using imx exporter dint have the time to play around with this.

**Comment by peimanja** [comment]
> We got Artifactory Pro
> information from System Info
> artifactory.running.mode: | PRO
> 
> exporter work's fine.
> 
> Thx a lot for your job

Thanks for updating this issue
