### ISSUE TITLE
Error creating the config. err: `ARTI_USERNAME` and `ARTI_PASSWORD` or `ARTI_ACCESS_TOKEN` environment variable hast to be set  source="artifactory_exporter.go:20"

### ISSUE THREAD

**Issue by udaymadu** [peimanja/artifactory_exporter#39]
Do we need to pass username& password or token in config  and rebuild it and then ran to install binary, dont see an option to directly run it by passing as options for those 3 vaules.

**Comment by gearedJP** [comment]
I know it's closed but I am seeing the same issue even I set the environment variables as below:
env | grep ARTI
ARTI_USERNAME=*********
ARTI_PASSWORD=*********

However I'm still seeing this error when I start the service:
Aug 24 10:44:32 ip-172-26-4-158 systemd: Started Artifactory Exporter.
Aug 24 10:44:32 ip-172-26-4-158 artifactory_exporter: time="2020-08-24T10:44:32Z" level=error msg="Error creating the config. err: `ARTI_USERNAME` and `ARTI_PASSWORD` or `ARTI_ACCESS_TOKEN` environment variable hast to be set" source="artifactory_exporter.go:20"
Aug 24 10:44:32 ip-172-26-4-158 systemd: artifactory_exporter.service: main process exited, code=exited, status=1/FAILURE
Aug 24 10:44:32 ip-172-26-4-158 systemd: Unit artifactory_exporter.service entered failed state.
Aug 24 10:44:32 ip-172-26-4-158 systemd: artifactory_exporter.service failed.

Thank you for your help in advance.
