### ISSUE TITLE
Unmarshall error

### ISSUE THREAD

**Issue by udaymadu** [peimanja/artifactory_exporter#40]
I am getting unmarshall error while fetching metrics in utils.go

level=error ts=2020-06-23T19:46:22.727Z caller=utils.go:47 msg="There was an error when trying to unmarshal the API Error" err="invalid character '<' looking for beginning of value"
level=error ts=2020-06-23T19:46:33.165Z caller=utils.go:47 msg="There was an error when trying to unmarshal the API Error" err="invalid character '<' looking for beginning of value"
level=error ts=2020-06-23T19:54:26.917Z caller=utils.go:47 msg="There was an error when trying to unmarshal the API Error" err="invalid character '<' looking for beginning of value"
level=error ts=2020-06-23T19:54:30.882Z caller=utils.go:47 msg="There was an error when trying to unmarshal the API Error" err="invalid character '<' looking for beginning of value"
level=error ts=2020-06-23T22:18:50.157Z caller=utils.go:47 msg="There was an error when trying to unmarshal the API Error" err="invalid character '<' looking for beginning of value"

**Comment by peimanja** [comment]
Can you please share more information like what version of Artifactory you are running? what liecense are you using? what version of exporter are you running? binary or the container

**Comment by udaymadu** [comment]
artifactory version: Artifactory Enterprise
6.17.0

licence entrprise
using docker image and deployed into kubernetes.

**Comment by peimanja** [comment]
> artifactory version: Artifactory Enterprise
> 6.17.0
> 
> licence entrprise
> using docker image and deployed into kubernetes.
> passing credentials through secrets.

Please check the lastest image. Artifactory API probably is returning an error that is not in the expected format. The recent change will at least show you the error. Please comment back here as I am interested in seeing  the error
