### ISSUE TITLE
/api/replications endpoint doesn't exist

### ISSUE THREAD

**Issue by barney-garrett** [peimanja/artifactory_exporter#43]
Looks like you are calling /api/replications which according to the documentation and my testing on v6.4 and v6.8 (Enterprise License) doesn't actually exist in this form.

Error messages in logs :
level=debug ts=2020-07-01T15:08:44.638Z caller=replication.go:29 msg="Fetching replications stats"
level=debug ts=2020-07-01T15:08:44.638Z caller=utils.go:24 msg="Fetching http" path=http://localhost:8081/artifactory/api/replications
level=error ts=2020-07-01T15:08:44.649Z caller=utils.go:53 msg="There was an error making API call" endpoint=http://localhost:8081/artifactory/api/replications err="Not Found" status=404
level=error ts=2020-07-01T15:08:44.649Z caller=replication.go:14 msg="Couldn't scrape Artifactory when fetching replications" err="Not Found"

and then because of the return 0 in the error catch in collector.go none of the other metrics are scraped : 
https://github.com/peimanja/artifactory_exporter/blob/48827804e60076fc770845154044b29395f098e7/collector/collector.go#L137

There is : 

1. /api/replications/{repoKey} - https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-GetRepositoryReplicationConfiguration
2. /api/system/replications - https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-GetRemoteRepositoriesRegisteredforReplication

Based on the rest of your code I think you mean the first one to get all the replication configs for each repo but to do that you are going to need to get the list of repo's and iterate over them.

as a temporary fix I've removed that block and it is now working without error.
https://github.com/barney-garrett/artifactory_exporter/commit/43de3e3495806c92897aa11f73efc6bf14592086

Edit : using the Binary version

**Comment by molu8bits** [comment]
I have the same problem with 6.8 version. 
/api/replications didn't exist and get 404
I guess that might be an error when there is no replication configured (my case). 
Anyway to overcome this issue temporarily I have edited  collector/replication.go
and replaced line 16:
`		return err`
with:
`		return nil`

Which just informs that replication metrics are not available but the rest works.
