### ISSUE TITLE
Artifactory JMX metrics with artifactory_exporter

### ISSUE THREAD

**Issue by padremortius** [peimanja/artifactory_exporter#45]
Do you planning to get JMX metrics from Artifactory server with artifactory_exporter?

**Comment by peimanja** [comment]
Unfortunately no. Last I checked there are no JMX bindings for Golang, and even then you can't load Go code into a JVM in order to be a Java agent. You can use [jmx_exporter](https://github.com/prometheus/jmx_exporter) to collect those metrics
