### ISSUE TITLE
Feasibility for Artifactory Version 5.11.6

### ISSUE THREAD

**Issue by GBASIN1** [peimanja/artifactory_exporter#46]
As in documentation, it is mentioned that this is tested on version 6.16.0. 
When I am trying this with my Artifactory **version 5.11.6**, I am getting an error saying _"Can't scrape Artifactory when fetching replications" err="HTTP status 405"_.
My Artifactory is licensed with type: **Commercial** 
Can you please clarify if the Artifactory exporter will work for version 5.11.6 or not?

**Comment by peimanja** [comment]
@GBASIN1 can you please set the `--log.level=debug` and see if you get more informations?

**Comment by peimanja** [comment]
closing this issue. Please open if you are still having issues
