### ISSUE TITLE
Enable artifactory_artifacts* metrics

### ISSUE THREAD

**Issue by DmytroBilanKaReen** [peimanja/artifactory_exporter#62]
Hi 
I'm using Artifactory enterprise 7.21.12 and want to use your exporter for artifactory monitoring.
I run exporter from binary and get all metrics excluding artifactory_artifacts* metrics. Haw to enable it?

**Comment by martinm82** [comment]
I have the same problem. We have 3 times more artifacts than @redecor-integration and I believe the problem is that it takes just longer to calculate the metrics.

**Comment by peimanja** [comment]
Interesting. Normally AQL is super fast and should handle that without any issue. any increment in API error in metrics? or anything in the logs? 

you can increase the Artifactory timeout (default is 5s) and see if that helps

**Comment by martinm82** [comment]
We have in total 350 repositories and roughly 40 million artifacts. The problem seems to be with the `artifactory_artifacts_created_Xm` metrics.

**Comment by peimanja** [comment]
>We have in total 350 repositories and roughly 40 million artifacts. The problem seems to be with the artifactory_artifacts_created_Xm metrics.
so yes, I'm saying for these `artifactory_artifacts_created_` metrics maybe it's taking more than 5 sec hence the exporter is timing out on those requests. increasing the Artifactory timeout might resolve the issue if you really want those metrics.

optionally we can provide a way to disable these metrics if that’s what you want.

**Comment by martinm82** [comment]
We have now reduced the scraping interval and as well implemented caching on nginx side to avoid overloading Artifactory with the queries.

**Comment by DmytroBilanKaReen** [comment]
@martinm82 can you share your solution for resolv?

**Comment by martinmigasiewicz-tomtom** [comment]
This is part of our nginx configuration we added for caching prometheus results by using Ansible:

```
upstream artifactory-metrics-exporter {
  server {{ ansible_default_ipv4.address }}:{{ artifactory_metrics_port }};
}

[...]

location /prometheus/ {
        proxy_cache prometheus-cache;
        proxy_cache_valid 60s;
        proxy_read_timeout  2400s;
        proxy_pass http://artifactory-metrics-exporter/prometheus/;
   }
```
