### ISSUE TITLE
Wrong license endpoint

### ISSUE THREAD

**Issue by martinm82** [peimanja/artifactory_exporter#64]
#### Overview of the Issue

Based on https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-LicenseInformation the license endpoint is called `licenses` and not `license` as defined here: https://github.com/peimanja/artifactory_exporter/blob/master/artifactory/system.go#L12

At least this is for Artifactory 7.x. Maybe it was like that in 6.x

### Logs

Log output of exporter when running and you try to get metrics from the metric path.

**Comment by peimanja** [comment]
Thanks @martinm82, we are also on version 7.x and I just confirmed both `license` and `licences` endpoints exists. maybe they kept it for backward compatibility. So I'm going to leave this as it is in case we break things for people on 6.x version
