### ISSUE TITLE
Log format doesn't change anything

### ISSUE THREAD

**Issue by Feriman22** [peimanja/artifactory_exporter#69]
Dear Developer,

I run this software on our server, but the output on the `servername:9531/metrics` site doesn't change at all.

I tried to run it with these ways:

```
./artifactory_exporter
./artifactory_exporter --log.format=json
./artifactory_exporter --log.format=logfmt
```

We got same format as an output for all methods. The target is reading these infos by Grafana, but the error is this below at this moment, while trying to add Prometheus data source:
`Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html> |..., bigger context ...|<html> <head><title>JFrog Artifactory |...`

What am I doing wrong?

Thanks!
Feriman

**Comment by peimanja** [comment]
hey @Feriman22 , Are you trying to point to the exporter from Grafana as Prometheus data source? if yes, that's not possible. you have to have a Prometheus server running and collect metrics exported by this exporter. Then you can point to your prometheus server.

I'll have to look at the log format :)

**Comment by peimanja** [comment]
log.format flag is working as expected:
```
./artifactory_exporter --artifactory.scrape-uri=https://**** --log.format=json
{"caller":"artifactory_exporter.go:30","level":"info","msg":"Starting artifactory_exporter","ts":"2022-02-16T03:44:18.585Z","version":"(version=, branch=, revision=)"}
{"caller":"artifactory_exporter.go:31","context":"(go=go1.17.2, user=, date=)","level":"info","msg":"Build context","ts":"2022-02-16T03:44:18.586Z"}
{"address":":9531","caller":"artifactory_exporter.go:32","level":"info","msg":"Listening on address","ts":"2022-02-16T03:44:18.586Z"}
```

**Comment by Feriman22** [comment]
Hi @peimanja 

Thanks for your quick answer! You're right, that was the issue.

The weird thing is we cannot see all metrics what we should to see:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/22872515/154484825-c26288d2-6505-4d75-b9d3-b45dc966a87f.png)

Do you have any idea why?


Thanks!

**Comment by peimanja** [comment]
hey @Feriman22 enable the debug level logging and see if there is something going on there `--log.level=debug`

you can also check `artifactory_exporter_total_api_errors` and `artifactory_exporter_json_parse_failures` metrics to see if they are greater than 0. That indicates if there was an issue during the scrape and parsing of stats from Artifactory

**Comment by peimanja** [comment]
I think the issue is with your Artifactory URL. `--artifactory.scrape-uri` normally looks like `https://ourafserver.com/artifactory` not `https://ourafserver.com/ui`

**Comment by Feriman22** [comment]
It should be `/ui` at the end, because we use Artifactory 7, where the URL has been changed from `/artifactory` to `/ui`

**Comment by peimanja** [comment]
> It should be `/ui` at the end, because we use Artifactory 7, where the URL has been changed from `/artifactory` to `/ui`

Give the `/artifactory` path a try. for API it is still `/artifactory`. [docs](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API+V2)

**Comment by Feriman22** [comment]
Hi @peimanja 

You're right, the problem was with the URL, we have to use `/artifactory` instead of `/ui`

Many thanks for your help and have a nice week! :)

Feriman
