### ISSUE TITLE
Dashboard panel: Add a timeseries panel for artifactory_storage_artifacts artifactory_storage_binaries

### ISSUE THREAD

**Issue by zhan9san** [peimanja/artifactory_exporter#72]
#### Feature Description

Would it be possible to add a timeseries panel for artifactory_storage_artifacts artifactory_storage_binaries?

#### Use Case(s)

We have many nightly builds, which publishes the artifacts, and we want to get the trends of artifacts count and binaries count.

It would be better to have a timeseries panel for Binaries size and artifacts size as well.

**Comment by peimanja** [comment]
Hey @zhan9san, so the metrics are available and you should be able to easily add those panels in Grafana or Datadog, ..
https://github.com/peimanja/artifactory_exporter/blob/master/grafana/dashboard.json dashboard is just an example and you should tweak it as you need.
