### ISSUE TITLE
fetch limited data from artifactory 

### ISSUE THREAD

**Issue by dineshpsalm** [peimanja/artifactory_exporter#73]
Hi team, 
Thanks for creating this exporter. I have recently used it and able to connect and fetch data but I don't know why its limited to only few parameters (Prometheus query screenshot attached). Any idea about it? 

![2022-04-01 00_45_26-4  ARTIF1WABAC001 ( Artifactory Acpt )](https://user-images.githubusercontent.com/59183645/161556030-a37f29b5-b11c-4da5-86b0-734dcbd0490d.jpg)
![2022-04-01 00_43_42-Prometheus Time Series Collection and Processing Server](https://user-images.githubusercontent.com/59183645/161556188-5f7be0d3-9cfb-4725-85eb-67e092ed53f2.jpg)

**Comment by peimanja** [comment]
hey @dineshpsalm, Thanks for trying out this exporter. As you can see in the logs, looks like there is an error. Please try out the latest release as it might provide better logging. But looks like some config issue. `artifactory.scrape-uri` normally is something like "https://<BASE_URL>/artifactory"

**Comment by dineshpsalm** [comment]
> hey @dineshpsalm, Thanks for trying out this exporter. As you can see in the logs, looks like there is an error. Please try out the latest release as it might provide better logging. But looks like some config issue. `artifactory.scrape-uri` normally is something like "https://<BASE_URL>/artifactory"
