### ISSUE TITLE
Fetch Interval

### ISSUE THREAD

**Issue by EvertonSA** [peimanja/artifactory_exporter#82]
Can I configure the scrap interval time to a higher one? lets say scrap every 5 minutes

**Comment by peimanja** [comment]
Hey @EvertonSA, basically every time prometheus scrape the exporter, exporter will fetch the info from Artifactory.
So it is all depend on your job [scrape_interval](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)
