### ISSUE TITLE
Helm existing secret failure

### ISSUE THREAD

**Issue by kononovbolt** [peimanja/artifactory_exporter#86]
In helm values if set existingSecret: true, the manifest gets render error.
envFrom:
        - secretRef:
           name: %!s(bool=true)

Error: YAML parse error on prometheus-artifactory-exporter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: found character that cannot start any token

**Comment by peimanja** [comment]
Hey @kononovbolt Please open an issue in https://github.com/peimanja/helm-charts repo
