### ISSUE TITLE
Package release

### ISSUE THREAD

**Issue by nerrehmit** [peimanja/artifactory_exporter#87]
Up until release v1.9.4 there were several packages released along with the source code. 
For example the packages for Linux 32/64 bit.

Release v1.9.5 from a couple days ago "only" shows the source code. 
Was this a one-off or are all future releases only going to be source code?

Thanks for any feedback.

**Comment by peimanja** [comment]
Thanks for reporting this. It should be fixed now https://github.com/peimanja/artifactory_exporter/releases/tag/v1.9.5
