### ISSUE TITLE
No metric named 'artifactory_artifacts_created_1m' and so on..

### ISSUE THREAD

**Issue by king4sun** [peimanja/artifactory_exporter#89]
Hello there,
when I ran this exporter and push data to Prometheus and show dashboard in Grafana, I came into a problem: **artifactory_artifacts_created_1m**, **artifactory_artifacts_downloaded_1m** and so on are missing.

The dashboard file is also created by peimanja from [here](https://grafana.com/grafana/dashboards/12113-artifactory-prometheus-exporter/)

The exporter version is v1.9.5.

Do you know why the metric is lost and the solution?

**Comment by peimanja** [comment]
Hey @king4sun, do you have many artifacts getting pushed or downloaded from Artifactory? Looks like the query is timing out. the default timeout is `5s` but try increasing it and see if that resolve your issue.

if you are using the helm chart:
```yaml
options:
  timeout: 10s
```

you can set time out using `--artifactory.timeout=10s` flag or set the `ARTI_TIMEOUT` environment variable
