### ISSUE TITLE
Add Federated repository Status Metrics

### ISSUE THREAD

**Issue by vgupta0309demonware** [peimanja/artifactory_exporter#92]
#### Feature Description

It would be awesome if the exporter could additionally monitor Federated repo statuses.
https://www.jfrog.com/confluence/display/JFROG/Working+with+Federated+Repositories#WorkingwithFederatedRepositories-monitor_fed_repos

That information is already available via the Artifactory API:
```
GET api/Federation/status/repo/<example-repo-local>
GET api/Federation/status/mirrorsLag
GET api/federation/status/unavailableMirrors
```
API Doc: 
https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-GetFederatedRepositoryStatus

#### Use Case(s)
This would be great for monitoring the Federated repository Status to track any issues there.

**Comment by vgupta0309** [comment]
@peimanja Any timeline on when you will be able to get this functionality added ?
Thanks for making this exporter and adding more functionalities.

**Comment by peimanja** [comment]
@vgupta0309 get the `canary` tag a try and report back please. I added these metrics as part of [optional-metrics](https://github.com/peimanja/artifactory_exporter#optional-metrics) so you need to enable it by passing `--optional-metric=federation_status` or if you are using helm:

```yaml
options:
...
  optionalMetrics:
    # - replication_status
    - federation_status
```

**Comment by vgupta0309** [comment]
Thanks for making this change, It's working as expected for:
```
GET api/Federation/status/mirrorsLag
GET api/federation/status/unavailableMirrors
```
Verified. 🟢 

Ref:  federation status per repo is heavy on Artifactory. Its removed from metrics to avoid impacting Artifactory performance
https://github.com/peimanja/artifactory_exporter/pull/98
