### ISSUE TITLE
Some metrics cannot be queried

### ISSUE THREAD

**Issue by zio-pzl** [peimanja/artifactory_exporter#93]
**problem statement**
When I started the exporter, I found that some metrics were missing, as follows:
`artifactory_artifacts_created_1m`
`artifactory_artifacts_downloaded_1m`
So the Grafana I configured has no monitoring data

In addition, I also failed to use --optional-metric, please help me to look at these problems
![image](https://user-images.githubusercontent.com/49870898/216216909-e59c4e7a-a114-4bf8-b02e-ae3e7b8af30f.png)

**other information**
Prometheus_exporter version：v1.11.0
Artifactory version：6.17.0

**Comment by zio-pzl** [comment]
The existing metrics are as follows:
![image](https://user-images.githubusercontent.com/49870898/216218143-bfd9c98a-69eb-49c9-9d47-b0e3fa64bf25.png)

**Comment by peimanja** [comment]
hey @zio-pzl, artifactory_artifacts_created_1m and artifactory_artifacts_downloaded_1m are enabled by default. Set the log level to `debug` and provide me with logs and maybe find something in there. 

the default timeout is `5s`, try setting it up to higher value and see if that resolves your issue via `--artifactory.timeout=15s` flag or `ARTI_TIMEOUT=15s` environment variable.

**Comment by tv-akuzmin** [comment]
Same problem
Prometheus_exporter version：v1.13.2
Artifactory version：7.55.3

This metrics is missing in debug logs
